env:
  node: true
  browser: true
  es2021: true
extends:
  - "airbnb-base"
  - 'plugin:jest/recommended'


overrides: []
parserOptions:
  ecmaVersion: latest
  

rules:
  import/no-extraneous-dependencies: 
    - off
  no-console: 0
  import/extensions: 
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  quotes: 0
